-- Tạo bảng NAMHOC
CREATE TABLE NAMHOC (
    MaNamHoc CHAR(10) PRIMARY KEY,
    Nam1 INT,
    Nam2 INT
);

-- Tạo bảng KHOILOP
CREATE TABLE KHOILOP (
    MaKhoi CHAR(10) PRIMARY KEY,
    TenKhoi NVARCHAR(50)
);

-- Tạo bảng LOP
CREATE TABLE LOP (
    MaLop CHAR(10) PRIMARY KEY,
    TenLop NVARCHAR(50),
    MaKhoi CHAR(10),
    FOREIGN KEY (MaKhoi) REFERENCES KHOILOP(MaKhoi)
);

-- Tạo bảng DANHSACHLOP
CREATE TABLE DANHSACHLOP (
    MaDanhSachLop CHAR(10) PRIMARY KEY,
    MaNamHoc CHAR(10),
    MaLop CHAR(10),
    SiSo INT,
    FOREIGN KEY (MaNamHoc) REFERENCES NAMHOC(MaNamHoc),
    FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
);

-- Tạo bảng HOCSINH
CREATE TABLE HOCSINH (
    MaHocSinh CHAR(10) PRIMARY KEY,
    TenHocSinh NVARCHAR(50),
    NgaySinh DATE,
    DiaChi NVARCHAR(100),
    Email NVARCHAR(100)
);

-- Tạo bảng CT_DSL
CREATE TABLE CT_DSL (
    MaCT_DSL CHAR(10) PRIMARY KEY,
    MaDanhSachLop CHAR(10),
    MaHocSinh CHAR(10),
    FOREIGN KEY (MaDanhSachLop) REFERENCES DANHSACHLOP(MaDanhSachLop),
    FOREIGN KEY (MaHocSinh) REFERENCES HOCSINH(MaHocSinh)
);

-- Tạo bảng THAMSO
CREATE TABLE THAMSO (
    TuoiHocSinhToiThieu INT,
    TuoiHocSinhToiDa INT,
    SoLuongHocSinhToiDa INT,
    DiemToiDa FLOAT,
    DiemToiThieu FLOAT
);

-- Tạo bảng MONHOC
CREATE TABLE MONHOC (
    MaMonHoc CHAR(10) PRIMARY KEY,
    TenMonHoc NVARCHAR(50)
);

-- Tạo bảng HOCKY
CREATE TABLE HOCKY (
    MaHocKy CHAR(10) PRIMARY KEY,
    TenHocKy NVARCHAR(50)
);

-- Tạo bảng BC_TKMH
CREATE TABLE BC_TKMH (
    MaBC_TKM CHAR(10) PRIMARY KEY,
    MaNamHoc CHAR(10),
    MaMonHoc CHAR(10),
    MaHocKy CHAR(10),
    FOREIGN KEY (MaNamHoc) REFERENCES NAMHOC(MaNamHoc),
    FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc),
    FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHocKy)
);

-- Tạo bảng BC_TKHK
CREATE TABLE BC_TKHK (
    MaBC_TKHK CHAR(10) PRIMARY KEY,
    MaHocKy CHAR(10),
    MaDanhSachLop CHAR(10),
    SoLuongDat INT,
    TiLe FLOAT,
    FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHocKy),
    FOREIGN KEY (MaDanhSachLop) REFERENCES DANHSACHLOP(MaDanhSachLop)
);

-- Tạo bảng LOAIKIEMTRA
CREATE TABLE LOAIKIEMTRA (
    MaLKT CHAR(10) PRIMARY KEY,
    TenLKT NVARCHAR(50),
    HeSo FLOAT
);

-- Tạo bảng BANGDIEM
CREATE TABLE BANGDIEM (
    MaBangDiem CHAR(10) PRIMARY KEY,
    MaCT_DSL CHAR(10),
    MaHocKy CHAR(10),
    DTBHK FLOAT,
    FOREIGN KEY (MaCT_DSL) REFERENCES CT_DSL(MaCT_DSL),
    FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHocKy)
);

-- Tạo bảng BD_MONHOC
CREATE TABLE BD_MONHOC (
    MaBD_MH CHAR(10) PRIMARY KEY,
    MaBangDiem CHAR(10),
    MaMonHoc CHAR(10),
    DTBMH FLOAT,
    FOREIGN KEY (MaBangDiem) REFERENCES BANGDIEM(MaBangDiem),
    FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc)
);

-- Tạo bảng BD_THANHPHAN
CREATE TABLE BD_THANHPHAN (
    MaBD_TP CHAR(10) PRIMARY KEY,
    MaBD_MH CHAR(10),
    MaLKT CHAR(10),
    KetQua FLOAT,
    FOREIGN KEY (MaBD_MH) REFERENCES BD_MONHOC(MaBD_MH),
    FOREIGN KEY (MaLKT) REFERENCES LOAIKIEMTRA(MaLKT)
);