DROP DATABASE quanlyhocsinh;

CREATE DATABASE quanlyhocsinh CHARACTER SET utf8mb4 COLLATE utf8mb4_vietnamese_ci;
use quanlyhocsinh;

-- Tạo bảng THAMSO
CREATE TABLE THAMSO (
    TuoiHocSinhToiThieu INT,
    TuoiHocSinhToiDa INT,
    SoLuongHocSinhToiDa INT,
    DiemToiDa FLOAT,
    DiemToiThieu FLOAT,
    DiemDat FLOAT
);

-- Tạo bảng NAMHOC
CREATE TABLE NAMHOC (
    MaNamHoc VARCHAR(255) PRIMARY KEY,
    Nam1 INT,
    Nam2 INT
);

-- Tạo bảng HOCKY
CREATE TABLE HOCKY (
    MaHocKy INT AUTO_INCREMENT PRIMARY KEY,
    TenHocKy NVARCHAR(50)
);
INSERT INTO HOCKY (MaHocKy, TenHocKy) VALUES ('1', 'Học kỳ I'), ('2', 'Học kỳ II');

-- Tạo bảng LOAIKIEMTRA
CREATE TABLE LOAIKIEMTRA (
    MaLKT INT PRIMARY KEY,
    TenLKT NVARCHAR(50),
    HeSo FLOAT
);
INSERT INTO LOAIKIEMTRA (MaLKT, TenLKT, HeSo) VALUES ('1', '15 phút', '1'), ('2', '1 tiết', '2'), ('3', 'học kỳ', '3');

-- Tạo bảng KHOILOP
CREATE TABLE KHOILOP (
    MaKhoi INT AUTO_INCREMENT PRIMARY KEY,
    TenKhoi NVARCHAR(50)
);

-- Tạo bảng LOP
CREATE TABLE LOP (
    MaLop INT AUTO_INCREMENT PRIMARY KEY,
    TenLop NVARCHAR(50),
    MaKhoi INT,
    FOREIGN KEY (MaKhoi) REFERENCES KHOILOP(MaKhoi)
);

-- Tạo bảng DANHSACHLOP
CREATE TABLE DANHSACHLOP (
    MaDanhSachLop INT AUTO_INCREMENT PRIMARY KEY,
    MaNamHoc VARCHAR(255),
    MaLop INT,
    SiSo INT,
    FOREIGN KEY (MaNamHoc) REFERENCES NAMHOC(MaNamHoc),
    FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
);

-- Tạo bảng HOCSINH
CREATE TABLE HOCSINH (
    MaHocSinh INT AUTO_INCREMENT PRIMARY KEY,
    TenHocSinh NVARCHAR(50),
    NgaySinh DATE,
    DiaChi NVARCHAR(100),
    Email NVARCHAR(100),
    GioiTinh NVARCHAR(10)
);

-- Tạo bảng CT_DSL
CREATE TABLE CT_DSL (
    MaCT_DSL INT AUTO_INCREMENT PRIMARY KEY,
    MaDanhSachLop INT,
    MaHocSinh INT,
    FOREIGN KEY (MaDanhSachLop) REFERENCES DANHSACHLOP(MaDanhSachLop),
    FOREIGN KEY (MaHocSinh) REFERENCES HOCSINH(MaHocSinh)
);

-- Tạo bảng MONHOC
CREATE TABLE MONHOC (
    MaMonHoc INT AUTO_INCREMENT PRIMARY KEY,
    TenMonHoc NVARCHAR(50),
    DiemDatMonHoc FLOAT
);

-- Tạo bảng BANGDIEM
CREATE TABLE BANGDIEM (
    MaBangDiem INT AUTO_INCREMENT PRIMARY KEY,
    MaCT_DSL INT,
    MaHocKy INT,
    DTBHK FLOAT,
    FOREIGN KEY (MaCT_DSL) REFERENCES CT_DSL(MaCT_DSL),
    FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHocKy)
);

-- Tạo bảng BD_MONHOC
CREATE TABLE BD_MONHOC (
    MaBD_MH INT AUTO_INCREMENT PRIMARY KEY,
    MaBangDiem INT,
    MaMonHoc INT,
    DTBMH FLOAT,
    FOREIGN KEY (MaBangDiem) REFERENCES BANGDIEM(MaBangDiem),
    FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc)
);

-- Tạo bảng BD_THANHPHAN
CREATE TABLE BD_THANHPHAN (
    MaBD_TP INT AUTO_INCREMENT PRIMARY KEY,
    MaBD_MH INT,
    MaLKT INT,
    KetQua FLOAT,
    FOREIGN KEY (MaBD_MH) REFERENCES BD_MONHOC(MaBD_MH),
    FOREIGN KEY (MaLKT) REFERENCES LOAIKIEMTRA(MaLKT),

    UNIQUE KEY (MaBD_MH, MaLKT)
);

-- Tạo bảng BC_TKMH
CREATE TABLE BC_TKMH (
    MaBC_TKM INT AUTO_INCREMENT PRIMARY KEY,
    MaNamHoc VARCHAR(255),
    MaMonHoc INT,
    MaHocKy INT,
    FOREIGN KEY (MaNamHoc) REFERENCES NAMHOC(MaNamHoc),
    FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc),
    FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHocKy)
);

-- Tạo bảng BC_TKHK
CREATE TABLE BC_TKHK (
    MaBC_TKHK INT AUTO_INCREMENT PRIMARY KEY,
    MaHocKy INT,
    MaDanhSachLop INT,
    SoLuongDat INT,
    TiLe FLOAT,
    FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHocKy),
    FOREIGN KEY (MaDanhSachLop) REFERENCES DANHSACHLOP(MaDanhSachLop)
);
